[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "hjmr", email = "2620990+hjmr@users.noreply.github.com"},
]
dependencies = [
    "simpleai>=0.8.3",
    "gensim>=4.2.0",
    "numpy>=1.23.5",
]
requires-python = ">=3.10"
license = {text = "MIT"}
